export const FETCH_MISSION_LIST_REQUEST = 'FETCH_MISSION_REQUEST';
export const FETCH_MISSION_LIST_SUCCESS = 'FETCH_MISSION_SUCCESS';

export const CREATE_MISSION_ITEM_REQUEST = 'CREATE_MISSION_ITEM_REQUEST';
export const CREATE_MISSION_ITEM_SUCCESS = 'CREATE_MISSION_ITEM_SUCCESS';

export const FETCH_MISSION_ITEM_REQUEST = 'FETCH_MISSION_ITEM_REQUEST';
export const FETCH_MISSION_ITEM_SUCCESS = 'FETCH_MISSION_ITEM_SUCCESS';

export const PATCH_MISSION_ITEM_REQUEST = 'PATCH_MISSION_ITEM_REQUEST';
export const PATCH_MISSION_ITEM_SUCCESS = 'PATCH_MISSION_ITEM_SUCCESS';

export const FETCH_MISSION_SECOND_PHASE_REQUEST = 'FETCH_MISSION_SECOND_PHASE_REQUEST';
export const FETCH_MISSION_SECOND_PHASE_SUCCESS = 'FETCH_MISSION_SECOND_PHASE_SUCCESS';

export const PATCH_MISSION_SECOND_PHASE_REQUEST = 'PATCH_MISSION_SECOND_PHASE_REQUEST';
export const PATCH_MISSION_SECOND_PHASE_SUCCESS = 'PATCH_MISSION_SECOND_PHASE_SUCCESS';

export const FETCH_MISSION_THIRD_PHASE_REQUEST = 'FETCH_MISSION_THIRD_PHASE_REQUEST';
export const FETCH_MISSION_THIRD_PHASE_SUCCESS = 'FETCH_MISSION_THIRD_PHASE_SUCCESS';

export const PATCH_MISSION_THIRD_PHASE_REQUEST = 'PATCH_MISSION_THIRD_PHASE_REQUEST';
export const PATCH_MISSION_THIRD_PHASE_SUCCESS = 'PATCH_MISSION_THIRD_PHASE_SUCCESS';

export const FETCH_MISSION_FOURTH_PHASE_REQUEST = 'FETCH_MISSION_FOURTH_PHASE_REQUEST';
export const FETCH_MISSION_FOURTH_PHASE_SUCCESS = 'FETCH_MISSION_FOURTH_PHASE_SUCCESS';

export const PATCH_MISSION_FOURTH_PHASE_REQUEST = 'PATCH_MISSION_FOURTH_PHASE_REQUEST';
export const PATCH_MISSION_FOURTH_PHASE_SUCCESS = 'PATCH_MISSION_FOURTH_PHASE_SUCCESS';
